#!/bin/bash

fstore create hello
fstore create world


fstore add --bucket=hello $(find -name *.cpp)
fstore add --bucket=world $(find -name *.cpp)

fstore add --bucket=hello $(find -name *.o)

uuid=$(fstore add --bucket=world Makefile)
uuid=$(cut -d ' ' -f 1 <(echo $uuid))

fstore object_remove --bucket=world $uuid
